version: '3'
services:
  python3:
    command: jupyter notebook --ip=0.0.0.0 --allow-root
    build:
      context: .
      dockerfile: ./docker/python3/Dockerfile
    ports:
      - "8888:8888"
    tty: true
    volumes:
      - .:/app
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3688:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
